package nhl.fantasyleague.simulator.game.NHLFantasyLeague.components;

import nhl.fantasyleague.simulator.game.NHLFantasyLeague.models.Coach;
import nhl.fantasyleague.simulator.game.NHLFantasyLeague.models.Player;
import nhl.fantasyleague.simulator.game.NHLFantasyLeague.models.Team;
import nhl.fantasyleague.simulator.game.NHLFantasyLeague.repositories.CoachRepository;
import nhl.fantasyleague.simulator.game.NHLFantasyLeague.repositories.PlayerRepository;
import nhl.fantasyleague.simulator.game.NHLFantasyLeague.repositories.TeamRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Component
public class DataLoader implements ApplicationRunner {

    @Autowired
    TeamRepository teamRepository;

    @Autowired
    PlayerRepository playerRepository;

    @Autowired
    CoachRepository coachRepository;

    public DataLoader(){

    }

    public void run(ApplicationArguments args){

//        TEAMS

        Team yotes = new Team("Arizona Coyotes", 50000000L, "Gila River Arena", "Glendale, AZ");
        teamRepository.save(yotes);
        Team bruins = new Team("Boston Bruins", 10000000L, "TD Garden", "Boston, MA");
        teamRepository.save(bruins);
        Team flames = new Team("Calgary Flames",10000000L, "Scotiabank Saddledome", "Calgary, AB");
        teamRepository.save(flames);
        Team canes = new Team("Carolina Hurricanes", 10000000L, "PNC Arena", "Raleigh, NC");
        teamRepository.save(canes);
        Team hawks = new Team("Chicago Blackhawks", 25000000L, "United Center", "Chicago, IL");
        teamRepository.save(hawks);
        Team avs = new Team("Colorado Avalanche", 10000000L, "Pepsi Center", "Denver, CO");
        teamRepository.save(avs);
        Team stars = new Team("Dallas Stars", 10000000L, "American Airlines Center", "Dallas, TX");
        teamRepository.save(stars);
        Team oilers = new Team("Edmonton Oilers", 15000000L, "Rogers Place", "Edmonton, AB");
        teamRepository.save(oilers);
        Team panthers = new Team("Florida Panthers", 10000000L, "BB&T Center", "Sunrise, FL");
        teamRepository.save(panthers);
        Team kings = new Team("Los Angeles Kings", 15000000L, "Staples Center", "Los Angeles, CA");
        teamRepository.save(kings);
        Team wild = new Team("Minnesota Wild", 10000000L, "Xcel Energy Center", "St. Paul, MN");
        teamRepository.save(wild);
        Team habs = new Team("Montreal Canadiens", 30000000L, "Bell Center", "Montreal, QC");
        teamRepository.save(habs);
        Team preds = new Team("Nashville Predators", 35000000L, "Prudential Center", "Nashville, TN");
        teamRepository.save(preds);
        Team isles = new Team("New York Islanders", 10000000L, "Nassau Coliseum", "New York, NY");
        teamRepository.save(isles);
        Team rangers = new Team("New York Rangers", 10000000L, "Madison Square Garden", "New York, NY");
        teamRepository.save(rangers);
        Team flyers = new Team("Philadelphia Flyers", 20000000L, "Wells Fargo Center", "Philadelphia, PA");
        teamRepository.save(flyers);
        Team pens = new Team("Pittsburgh Penguins", 10000000L, "PPG Paints Arena", "Pittsburgh, PA");
        teamRepository.save(pens);
        Team blues = new Team("St. Louis Blues", 10000000L, "Enterprise Center", "St. Louis, MO");
        teamRepository.save(blues);
        Team tampa = new Team("Tampa Bay Lightning", 10000000L, "Amalie Arena", "Tampa, FL");
        teamRepository.save(tampa);
        Team leafs = new Team("Toronto Maple Leafs", 15000000L, "Scotiabank Arena", "Toronto, ON");
        teamRepository.save(leafs);
        Team knights = new Team("Vegas Golden Knights", 10000000L, "T-Mobile Arena", "Paradise, NV");
        teamRepository.save(knights);
        Team caps = new Team("Washington Capitals", 10000000L, "Capital One Arena", "Washington, DC");
        teamRepository.save(caps);
        Team jets = new Team("Winnipeg Jets", 15000000L, "Bell MTS Place", "Winnipeg, MB");
        teamRepository.save(jets);

//        PLAYER TEAM

        Team user = new Team("name", 300000000L, "stadium", "city");
        teamRepository.save(user);

//        FREE AGENT TEAM

        Team free = new Team("Free Agents", 0L, "N/A", "N/A");
        teamRepository.save(free);


//        COACHES

        Coach bBoudreau = new Coach("Bruce", "Boudreau", "Defensive",true, yotes);
        coachRepository.save(bBoudreau);
        Coach bCassidy = new Coach("Bruce", "Cassidy", "Defensive",true, bruins);
        coachRepository.save(bCassidy);
        Coach dSutter = new Coach("Darryl", "Sutter", "Defensive",true, flames);
        coachRepository.save(dSutter);
        Coach rBrindAmour = new Coach("Rod", "Brind'Amour", "Attacking",true, canes);
        coachRepository.save(rBrindAmour);
        Coach jColliton = new Coach("Jeremy", "Colliton", "Defensive",true, hawks);
        coachRepository.save(jColliton);
        Coach jBednar = new Coach("Jared", "Bednar", "Attacking",true, avs);
        coachRepository.save(jBednar);
        Coach rBowness = new Coach("Rick", "Bowness", "Defensive",true, stars);
        coachRepository.save(rBowness);
        Coach dTippett = new Coach("Dave", "Tippett", "Attacking",true, oilers);
        coachRepository.save(dTippett);
        Coach jQuenneville = new Coach("Joel", "Quenneville", "Attacking",true, panthers);
        coachRepository.save(jQuenneville);
        Coach tMcLellan = new Coach("Todd", "McLellan", "Defensive",true, kings);
        coachRepository.save(tMcLellan);
        Coach dEvason = new Coach("Dean", "Evason", "Attacking",true, wild);
        coachRepository.save(dEvason);
        Coach dDucharme = new Coach("Dominique", "Ducharme", "Defensive",true, habs);
        coachRepository.save(dDucharme);
        Coach jHynes = new Coach("John", "Hynes", "Defensive",true, preds);
        coachRepository.save(jHynes);
        Coach bTrotz = new Coach("Barry", "Trotz", "Defensive",true, isles);
        coachRepository.save(bTrotz);
        Coach gGallant = new Coach("Gerard", "Gallant", "Attacking",true, rangers);
        coachRepository.save(gGallant);
        Coach aVigneault = new Coach("Alain", "Vigneault", "Defensive",true, flyers);
        coachRepository.save(aVigneault);
        Coach mSullivan = new Coach("Mike", "Sullivan", "Attacking",true, pens);
        coachRepository.save(mSullivan);
        Coach cBerube = new Coach("Craig", "Berube", "Defensive",true, blues);
        coachRepository.save(cBerube);
        Coach jCooper = new Coach("Jon", "Cooper", "Attacking",true, tampa);
        coachRepository.save(jCooper);
        Coach sKeefe = new Coach("Sheldon", "Keefe", "Attacking",true, leafs);
        coachRepository.save(sKeefe);
        Coach pDeBoer = new Coach("Peter", "DeBoer", "Attacking",true, knights);
        coachRepository.save(pDeBoer);
        Coach pLaviolette = new Coach("Peter", "Laviolette", "Attacking",true, caps);
        coachRepository.save(pLaviolette);
        Coach pMaurice = new Coach("Paul", "Maurice", "Attacking",true, jets);
        coachRepository.save(pMaurice);

//        PLAYER PROFILE

        Coach player = new Coach("first", "last", "N/A", false, user);
        coachRepository.save(player);

//        PLAYERS

//        ARIZONA COYOTES

        Player cDvorak = new Player("Christian", "Dvorak", 25, "Center", 1, 2, 15000000, yotes);
        playerRepository.save(cDvorak);
        Player nSchmaltz = new Player("Nick", "Schmaltz", 25, "Center", 2, 1, 5000000, yotes);
        playerRepository.save(nSchmaltz);
        Player dBrassard = new Player("Derick", "Brassard", 33, "Center", 3, 1, 5000000, yotes);
        playerRepository.save(dBrassard);
        Player jLarsson = new Player("Johan", "Larsson", 28, "Left Wing", 1, 1, 5000000, yotes);
        playerRepository.save(jLarsson);
        Player lCrouse = new Player("Lawson", "Crouse", 24, "Left Wing", 2, 1, 5000000, yotes);
        playerRepository.save(lCrouse);
        Player dHunt = new Player("Dryden", "Hunt", 25, "Left Wing", 3, 1, 5000000, yotes);
        playerRepository.save(dHunt);
        Player pKessel = new Player("Phil", "Kessel", 33, "Right Wing", 1, 3, 30000000, yotes);
        playerRepository.save(pKessel);
        Player cKeller = new Player("Clayton", "Keller", 22, "Right Wing", 2, 2, 15000000, yotes);
        playerRepository.save(cKeller);
        Player cFischer = new Player("Christian", "Fischer", 24, "Right Wing", 3, 1, 5000000, yotes);
        playerRepository.save(cFischer);
        Player jChychrun = new Player("Jakob", "Chychrun", 23, "Defence", 1, 3, 30000000, yotes);
        playerRepository.save(jChychrun);
        Player oELarsson = new Player("Oliver", "Ekman-Larsson", 29, "Defence", 1, 3, 30000000, yotes);
        playerRepository.save(oELarsson);
        Player aGoligoski = new Player("Alex", "Goligoski", 35, "Defence", 2, 2, 15000000, yotes);
        playerRepository.save(aGoligoski);
        Player jOesterle = new Player("Jordan", "Oesterle", 29, "Defence", 2, 2, 15000000, yotes);
        playerRepository.save(jOesterle);
        Player iLyubushkin = new Player("Ilya", "Lyubushkin", 27, "Defence", 3, 1, 5000000, yotes);
        playerRepository.save(iLyubushkin);
        Player nHjalmarsson = new Player("Niklas", "Hjalmarsson", 34, "Defence", 3, 1, 5000000, yotes);
        playerRepository.save(nHjalmarsson);
        Player aHill = new Player("Adin", "Hill", 25, "Goaltender", 1, 3, 30000000, yotes);
        playerRepository.save(aHill);
        Player dKuemper = new Player("Darcy", "Kuemper", 31, "Goaltender", 2, 2, 15000000, yotes);
        playerRepository.save(dKuemper);
        Player aRaanta = new Player("Antti", "Raanta", 32, "Goaltender", 3, 2, 15000000, yotes);
        playerRepository.save(aRaanta);

//        BOSTON BRUINS

        Player pBergeron = new Player("Patrice", "Bergeron", 35, "Center", 1, 3, 30000000, bruins);
        playerRepository.save(pBergeron);
        Player dKrejci = new Player("David", "Krejci", 35, "Center", 2, 3, 30000000, bruins);
        playerRepository.save(dKrejci);
        Player cSmith = new Player("Craig", "Smith", 31, "Center", 3, 2, 15000000, bruins);
        playerRepository.save(cSmith);
        Player bMarchand = new Player("Brad", "Marchand", 33, "Left Wing", 1, 3, 30000000, bruins);
        playerRepository.save(bMarchand);
        Player tHall = new Player("Taylor", "Hall", 29, "Left Wing", 2, 3, 30000000, bruins);
        playerRepository.save(tHall);
        Player nRitchie = new Player("Nick", "Ritchie", 25, "Left Wing", 3, 2, 15000000, bruins);
        playerRepository.save(nRitchie);
        Player dPastrnak = new Player("David", "Pastrnak", 25, "Right Wing", 1, 3, 30000000, bruins);
        playerRepository.save(dPastrnak);
        Player cWagner = new Player("Chris", "Wagner", 30, "Right Wing", 2, 1, 5000000, bruins);
        playerRepository.save(cWagner);
        Player zSenyshyn = new Player("Zach", "Senyshyn", 24, "Right Wing", 3, 1, 5000000, bruins);
        playerRepository.save(zSenyshyn);
        Player cMcAvoy = new Player("Charlie", "McAvoy", 23, "Defence", 1, 3, 30000000, bruins);
        playerRepository.save(cMcAvoy);
        Player mGrzelcyk = new Player("Matt", "Grzelcyk", 27, "Defence", 1, 2, 15000000, bruins);
        playerRepository.save(mGrzelcyk);
        Player cClifton = new Player("Connor", "Clifton", 26, "Defence", 2, 2, 15000000, bruins);
        playerRepository.save(cClifton);
        Player jLauzon = new Player("Jeremy", "Lauzon", 24, "Defence", 2, 2, 15000000, bruins);
        playerRepository.save(jLauzon);
        Player jZboril = new Player("Jakub", "Zboril", 24, "Defence", 3, 1, 5000000, bruins);
        playerRepository.save(jZboril);
        Player bCarlo = new Player("Brandon", "Carlo", 24, "Defence", 3, 1, 5000000, bruins);
        playerRepository.save(bCarlo);
        Player tRask = new Player("Tuuka", "Rask", 34, "Goaltender", 1, 3, 30000000, bruins);
        playerRepository.save(tRask);
        Player jHalak = new Player("Jaroslav", "Halak", 36, "Goaltender", 2, 1, 5000000, bruins);
        playerRepository.save(jHalak);
        Player jSwayman = new Player("Jeremy", "Swayman", 22, "Goaltender", 3, 1, 5000000, bruins);
        playerRepository.save(jSwayman);

//        CALGARY FLAMES

        Player eLindholm = new Player("Elias", "Lindholm", 26, "Center", 1, 3, 30000000, flames);
        playerRepository.save(eLindholm);
        Player mBacklund = new Player("Mikael", "Backlund", 32, "Center", 2, 2, 15000000, flames);
        playerRepository.save(mBacklund);
        Player sMonahan = new Player("Sean", "Monahan", 26, "Center", 3, 2, 15000000, flames);
        playerRepository.save(sMonahan);
        Player jGaudreau = new Player("Johnny", "Gaudreau", 27, "Left Wing", 1, 3, 30000000, flames);
        playerRepository.save(jGaudreau);
        Player mTkachuk = new Player("Matthew", "Tkachuk", 23, "Left Wing", 2, 3, 30000000, flames);
        playerRepository.save(mTkachuk);
        Player aMangiapane = new Player("Andrew", "Mangiapane", 25, "Left Wing", 3, 3, 30000000, flames);
        playerRepository.save(aMangiapane);
        Player mLucic = new Player("Milan", "Lucic", 33, "Right Wing", 1, 2, 15000000, flames);
        playerRepository.save(mLucic);
        Player dDube = new Player("Dillon", "Dube", 22, "Right Wing", 2, 2, 15000000, flames);
        playerRepository.save(dDube);
        Player bRitchie = new Player("Brett", "Ritchie", 27, "Right Wing", 3, 1, 5000000, flames);
        playerRepository.save(bRitchie);
        Player mGiordano = new Player("Mark", "Giordano", 37, "Defence", 1, 3, 30000000, flames);
        playerRepository.save(mGiordano);
        Player cTanev = new Player("Christopher", "Tanev", 31, "Defence", 1, 3, 30000000, flames);
        playerRepository.save(cTanev);
        Player rAndersson = new Player("Rasmus", "Andersson", 24, "Defence", 2, 2, 15000000, flames);
        playerRepository.save(rAndersson);
        Player nHanifin = new Player("Noah", "Hanifin", 24, "Defence", 2, 2, 15000000, flames);
        playerRepository.save(nHanifin);
        Player jValimaki = new Player("Jusso", "Valimaki", 22, "Defence", 3, 2, 15000000, flames);
        playerRepository.save(jValimaki);
        Player nNesterov = new Player("Nikita", "Nesterov", 28, "Defence", 3, 1, 5000000, flames);
        playerRepository.save(nNesterov);
        Player jMarkstrom = new Player("Jacob", "Markstrom", 31, "Goaltender", 1, 3, 30000000, flames);
        playerRepository.save(jMarkstrom);
        Player lDomingue = new Player("Louis", "Domingue", 29, "Goaltender", 2, 1, 5000000, flames);
        playerRepository.save(lDomingue);
        Player aZagidulin = new Player("Artyom", "Zagidulin", 25, "Goaltender", 3, 1, 5000000, flames);
        playerRepository.save(aZagidulin);

//        CAROLINA HURRICANES

        Player sAho = new Player("Sebastian", "Aho", 23, "Center", 1, 3, 30000000, canes);
        playerRepository.save(sAho);
        Player vTrocheck = new Player("Vincent", "Trocheck", 27, "Center", 2, 3, 30000000, canes);
        playerRepository.save(vTrocheck);
        Player mNecas = new Player("Martin", "Necas", 22, "Center", 3, 3, 30000000, canes);
        playerRepository.save(mNecas);
        Player jStaal = new Player("Jordan", "Staal", 32, "Left Wing", 1, 3, 30000000, canes);
        playerRepository.save(jStaal);
        Player wFoegele = new Player("Warren", "Foegele", 25, "Left Wing", 2, 2, 15000000, canes);
        playerRepository.save(wFoegele);
        Player jMartinook = new Player("Jordan", "Martinook", 28, "Left Wing", 3, 1, 5000000, canes);
        playerRepository.save(jMartinook);
        Player aSvechnikov = new Player("Andrei", "Svechnikov", 21, "Right Wing", 1, 3, 30000000, canes);
        playerRepository.save(aSvechnikov);
        Player nNiederreiter = new Player("Nino", "Niederreiter", 28, "Right Wing", 2, 3, 30000000, canes);
        playerRepository.save(nNiederreiter);
        Player jFast = new Player("Jesper", "Fast", 29, "Right Wing", 3, 2, 15000000, canes);
        playerRepository.save(jFast);
        Player dHamilton = new Player("Dougie", "Hamilton", 28, "Defence", 1, 3, 30000000, canes);
        playerRepository.save(dHamilton);
        Player bPesce = new Player("Brett", "Pesce", 26, "Defence", 1, 3, 30000000, canes);
        playerRepository.save(bPesce);
        Player jSlavin = new Player("Jaccob", "Slavin", 27, "Defence", 2, 3, 30000000, canes);
        playerRepository.save(jSlavin);
        Player jBean = new Player("Jake", "Bean", 23, "Defence", 2, 2, 15000000, canes);
        playerRepository.save(jBean);
        Player bSkjei = new Player("Brady", "Skjei", 27, "Defence", 3, 2, 15000000, canes);
        playerRepository.save(bSkjei);
        Player jHakanpaa = new Player("Jani", "Hakanpaa", 29, "Defence", 3, 1, 5000000, canes);
        playerRepository.save(jHakanpaa);
        Player aNedeljkovic = new Player("Alex", "Nedeljkovic", 25, "Goaltender", 1, 3, 30000000, canes);
        playerRepository.save(aNedeljkovic);
        Player pMrazek = new Player("Petr", "Mrazek", 29, "Goaltender", 2, 2, 15000000, canes);
        playerRepository.save(pMrazek);
        Player jReimer = new Player("James", "Reimer", 33, "Goaltender", 3, 1, 5000000, canes);
        playerRepository.save(jReimer);

//        CHICAGO BLACKHAWKS

        Player pSuter = new Player("Pius", "Suter", 25, "Center", 1, 2, 15000000, hawks);
        playerRepository.save(pSuter);
        Player pKurashev = new Player("Philipp", "KuraShev", 21, "Center", 2, 1, 5000000, hawks);
        playerRepository.save(pKurashev);
        Player dKampf = new Player("David", "Kampf", 26, "Center", 3, 1, 5000000, hawks);
        playerRepository.save(dKampf);
        Player aDebrincat = new Player("Alex", "Debrincat", 23, "Left Wing", 1, 3, 30000000, hawks);
        playerRepository.save(aDebrincat);
        Player dKubalik = new Player("Dominik", "Kubalik", 25, "Left Wing", 2, 3, 30000000, hawks);
        playerRepository.save(dKubalik);
        Player bHagel = new Player("Brandon", "Hagel", 22, "Left Wing", 3, 2, 15000000, hawks);
        playerRepository.save(bHagel);
        Player pKane = new Player("Patrick", "Kane", 32, "Right Wing", 1, 3, 30000000, hawks);
        playerRepository.save(pKane);
        Player mJanmark = new Player("Mattias", "Janmark", 28, "Right Wing", 2, 2, 15000000, hawks);
        playerRepository.save(mJanmark);
        Player dStrome = new Player("Dylan", "Strome", 24, "Right Wing", 3, 1, 5000000, hawks);
        playerRepository.save(dStrome);
        Player cMurphy = new Player("Connor", "Murphy", 28, "Defence", 1, 2, 15000000, hawks);
        playerRepository.save(cMurphy);
        Player aBoqvist = new Player("Adam", "Boqvist", 20, "Defence", 1, 2, 15000000, hawks);
        playerRepository.save(aBoqvist);
        Player dKeith = new Player("Duncan", "Keith", 37, "Defence", 2, 2, 15000000, hawks);
        playerRepository.save(dKeith);
        Player nZadorov = new Player("Nikita", "Zadorov", 26, "Defence", 2, 2, 15000000, hawks);
        playerRepository.save(nZadorov);
        Player cDeHaan = new Player("Calvin", "De Haan", 30, "Defence", 3, 1, 5000000, hawks);
        playerRepository.save(cDeHaan);
        Player iMitchell = new Player("Ian", "Mitchell", 22, "Defence", 3, 1, 5000000, hawks);
        playerRepository.save(iMitchell);
        Player kLankinen = new Player("Kevin", "Lankinen", 26, "Goaltender", 1, 3, 30000000, hawks);
        playerRepository.save(kLankinen);
        Player cDelia = new Player("Collin", "Delia", 27, "Goaltender", 2, 2, 15000000, hawks);
        playerRepository.save(cDelia);
        Player mSubban = new Player("Malcolm", "Subban", 27, "Goaltender", 3, 1, 5000000, hawks);
        playerRepository.save(mSubban);

//        COLORADO AVALANCHE

        Player nMacKinnon = new Player("Nathan", "MacKinnon", 25, "Center", 1, 3, 30000000, avs);
        playerRepository.save(nMacKinnon);
        Player nKadri = new Player("Nazem", "Kadri", 30, "Center", 2, 2, 15000000, avs);
        playerRepository.save(nKadri);
        Player tJost = new Player("Tyson", "Jost", 23, "Center", 3, 2, 15000000, avs);
        playerRepository.save(tJost);
        Player gLandeskog = new Player("Gabriel", "Landeskog", 28, "Left Wing", 1, 3, 30000000, avs);
        playerRepository.save(gLandeskog);
        Player aBurakovsky = new Player("Andre", "Burakovsky", 26, "Left Wing", 2, 3, 30000000, avs);
        playerRepository.save(aBurakovsky);
        Player bSaad = new Player("Brandon", "Saad", 28, "Left Wing", 3, 2, 15000000, avs);
        playerRepository.save(bSaad);
        Player mRantanen = new Player("Mikko", "Rantanen", 24, "Right Wing", 1, 3, 30000000, avs);
        playerRepository.save(mRantanen);
        Player jDonskoi = new Player("Joonas", "Donskoi", 29, "Right Wing", 2, 3, 30000000, avs);
        playerRepository.save(jDonskoi);
        Player vNichushkin = new Player("Valerie", "Nichushkin", 26, "Right Wing", 3, 2, 15000000, avs);
        playerRepository.save(vNichushkin);
        Player cMakar = new Player("Cale", "Makar", 22, "Defence", 1, 3, 30000000, avs);
        playerRepository.save(cMakar);
        Player sGirard = new Player("Samuel", "Girard", 23, "Defence", 1, 3, 30000000, avs);
        playerRepository.save(sGirard);
        Player dToews = new Player("Devon", "Toews", 27, "Defence", 2, 3, 30000000, avs);
        playerRepository.save(dToews);
        Player rGraves = new Player("Ryan", "Graves", 26, "Defence", 2, 2, 15000000, avs);
        playerRepository.save(rGraves);
        Player jMacDonald = new Player("Jacob", "MacDonald", 28, "Defence", 3, 2, 15000000, avs);
        playerRepository.save(jMacDonald);
        Player cTimmins = new Player("Conor", "Timmins", 22, "Defence", 3, 2, 15000000, avs);
        playerRepository.save(cTimmins);
        Player pGrubauer = new Player("Philipp", "Grubauer", 29, "Goaltender", 1, 3, 30000000, avs);
        playerRepository.save(pGrubauer);
        Player jJohansson = new Player("Jonas", "Johansson", 25, "Goaltender", 2, 1, 5000000, avs);
        playerRepository.save(jJohansson);
        Player dDubnyk = new Player("Devan", "Dubnyk", 35, "Goaltender", 3, 1, 5000000, avs);
        playerRepository.save(dDubnyk);

//        DALLAS STARS

        Player jPavelski = new Player("Joe", "Pavelski", 36, "Center", 1, 3, 30000000, stars);
        playerRepository.save(jPavelski);
        Player jDickinson = new Player("Jason", "Dickinson", 25, "Center", 2, 1, 5000000, stars);
        playerRepository.save(jDickinson);
        Player rFaksa = new Player("Radek", "Faksa", 27, "Center", 3, 1, 5000000, stars);
        playerRepository.save(rFaksa);
        Player jRobertson = new Player("Jason", "Robertson", 21, "Left Wing", 1, 3, 30000000, stars);
        playerRepository.save(jRobertson);
        Player rHintz = new Player("Roope", "Hintz", 24, "Left Wing", 2, 3, 30000000, stars);
        playerRepository.save(rHintz);
        Player jBenn = new Player("Jamie", "Benn", 31, "Left Wing", 3, 3, 30000000, stars);
        playerRepository.save(jBenn);
        Player dGurianov = new Player("Denis", "Gurianov", 24, "Right Wing", 1, 3, 30000000, stars);
        playerRepository.save(dGurianov);
        Player bComeau = new Player("Blake", "Comeau", 35, "Right Wing", 2, 1, 5000000, stars);
        playerRepository.save(bComeau);
        Player aCogliano = new Player("Andrew", "Cogliano", 34, "Right Wing", 3, 1, 5000000, stars);
        playerRepository.save(aCogliano);
        Player jKlingberg = new Player("John", "Klingberg", 28, "Defence", 1, 3, 30000000, stars);
        playerRepository.save(jKlingberg);
        Player mHeiskanen = new Player("Miro", "Heiskanen", 21, "Defence", 1, 3, 30000000, stars);
        playerRepository.save(mHeiskanen);
        Player eLindell = new Player("Esa", "Lindell", 27, "Defence", 2, 2, 15000000, stars);
        playerRepository.save(eLindell);
        Player jOleksiak = new Player("Jamie", "Oleksiak", 27, "Defence", 2, 2, 15000000, stars);
        playerRepository.save(jOleksiak);
        Player jHanley = new Player("Joel", "Hanley", 30, "Defence", 3, 2, 15000000, stars);
        playerRepository.save(jHanley);
        Player aSekera = new Player("Andrej", "Sekera", 35, "Defence", 3, 1, 5000000, stars);
        playerRepository.save(aSekera);
        Player sTaber = new Player("Spencer", "Taber", 34, "Goaltender", 1, 3, 30000000, stars);
        playerRepository.save(sTaber);
        Player aKhudobin = new Player("Anton", "Khudobin", 35, "Goaltender", 2, 2, 15000000, stars);
        playerRepository.save(aKhudobin);
        Player jOettinger = new Player("Jake", "Oettinger", 22, "Goaltender", 3, 2, 15000000, stars);
        playerRepository.save(jOettinger);

//        EDMONTON OILERS

        Player cMcDavid = new Player("Connor", "McDavid", 24, "Center", 1, 3, 30000000, oilers);
        playerRepository.save(cMcDavid);
        Player lDraisaitl = new Player("Leon", "Draisaitl", 25, "Center", 2, 3, 30000000, oilers);
        playerRepository.save(lDraisaitl);
        Player rNugentHopkins = new Player("Ryan", "Nugent-Hopkins", 28, "Center", 3, 2, 15000000, oilers);
        playerRepository.save(rNugentHopkins);
        Player hBrady = new Player("Holly", "Brady", 27, "Left Wing", 1, 3, 30000000, oilers);
        playerRepository.save(hBrady);
        Player dKahun = new Player("Dominik", "Kahun", 25, "Left Wing", 2, 1, 5000000, oilers);
        playerRepository.save(dKahun);
        Player jKhaira = new Player("Jujhar", "Khaira", 26, "Left Wing", 3, 1, 5000000, oilers);
        playerRepository.save(jKhaira);
        Player jPuljujarvi = new Player("Jesse", "Puljujarvi", 23, "Right Wing", 1, 2, 15000000, oilers);
        playerRepository.save(jPuljujarvi);
        Player kYamamoto = new Player("Kailer", "Yamamoto", 22, "Right Wing", 2, 2, 15000000, oilers);
        playerRepository.save(kYamamoto);
        Player aChiasson = new Player("Alex", "Chiasson", 30, "Right Wing", 3, 1, 5000000, oilers);
        playerRepository.save(aChiasson);
        Player tBarrie = new Player("Tyson", "Barrie", 29, "Defence", 1, 3, 30000000, oilers);
        playerRepository.save(tBarrie);
        Player dNurse = new Player("Darnell", "Nurse", 26, "Defence", 1, 3, 30000000, oilers);
        playerRepository.save(dNurse);
        Player aLarsson = new Player("Adam", "Larsson", 28, "Defence", 2, 2, 15000000, oilers);
        playerRepository.save(aLarsson);
        Player kRussell = new Player("Kris", "Russell", 34, "Defence", 2, 2, 15000000, oilers);
        playerRepository.save(kRussell);
        Player eBear = new Player("Ethan", "Bear", 24, "Defence", 3, 2, 15000000, oilers);
        playerRepository.save(eBear);
        Player cJones = new Player("Caleb", "Jones", 24, "Defence", 3, 1, 5000000, oilers);
        playerRepository.save(cJones);
        Player mSmith = new Player("Mike", "Smith", 39, "Goaltender", 1, 3, 3000000, oilers);
        playerRepository.save(mSmith);
        Player mKoskinen = new Player("Mikko", "Koskinen", 32, "Goaltender", 2, 2, 15000000, oilers);
        playerRepository.save(mKoskinen);
        Player sSkinner = new Player("Stuart", "Skinner", 22, "Goaltender", 3, 1, 5000000, oilers);
        playerRepository.save(sSkinner);

//        FLORIDA PANTHERS

        Player aBarkov = new Player("Aleksander", "Barkov", 25, "Center", 1, 3, 30000000, panthers);
        playerRepository.save(aBarkov);
        Player cVerhaeghe = new Player("Carter", "Verhaeghe", 25, "Center", 2, 3, 30000000, panthers);
        playerRepository.save(cVerhaeghe);
        Player aWennberg = new Player("Alex", "Wennberg", 26, "Center", 3, 2, 15000000, panthers);
        playerRepository.save(aWennberg);
        Player jHuberdeau = new Player("Jonathan", "Huberdeau", 28, "Left Wing", 1, 3, 30000000, panthers);
        playerRepository.save(jHuberdeau);
        Player aDuclair = new Player("Anthony", "Duclair", 25, "Left Wing", 2, 3, 30000000, panthers);
        playerRepository.save(aDuclair);
        Player mMarchment = new Player("Mason", "Marchment", 26, "Left Wing", 3, 1, 5000000, panthers);
        playerRepository.save(mMarchment);
        Player pHornqvist = new Player("Patric", "Hornqvist", 34, "Right Wing", 1, 3, 30000000, panthers);
        playerRepository.save(pHornqvist);
        Player fVatrano = new Player("Frank", "Vatrano", 27, "Right Wing", 2, 2, 15000000, panthers);
        playerRepository.save(fVatrano);
        Player oTippett = new Player("Owen", "Tippett", 22, "Right Wing", 3, 1, 5000000, panthers);
        playerRepository.save(oTippett);
        Player mWeegar = new Player("MacKenzie", "Weegar", 27, "Defence", 1, 3, 30000000, panthers);
        playerRepository.save(mWeegar);
        Player kYandle = new Player("Keith", "Yandle", 34, "Defence", 1, 3, 30000000, panthers);
        playerRepository.save(kYandle);
        Player aEkblad = new Player("Aaron", "Ekblad", 25, "Defence", 2, 2, 15000000, panthers);
        playerRepository.save(aEkblad);
        Player gForsling = new Player("Gustav", "Forsling", 25, "Defence", 2, 2, 15000000, panthers);
        playerRepository.save(gForsling);
        Player rGudas = new Player("Radko", "Gudas", 31, "Defence", 3, 1, 5000000, panthers);
        playerRepository.save(rGudas);
        Player mNutivaara = new Player("Markus", "Nutivaara", 27, "Defence", 3, 1, 5000000, panthers);
        playerRepository.save(mNutivaara);
        Player sBobrovsky = new Player("Sergei", "Bobrovsky", 32, "Goaltender", 1, 3, 30000000, panthers);
        playerRepository.save(sBobrovsky);
        Player cDriedger = new Player("Chris", "Driedger", 27, "Goaltender", 2, 3, 30000000, panthers);
        playerRepository.save(cDriedger);
        Player sKnight = new Player("Spencer", "Knight", 20, "Goaltender", 3, 2, 15000000, panthers);
        playerRepository.save(sKnight);

//        LOS ANGELES KINGS

        Player aKopitar = new Player("Anze", "Kopitar", 33, "Center", 1, 3, 30000000, kings);
        playerRepository.save(aKopitar);
        Player aKempe = new Player("Adrian", "Kempe", 24, "Center", 2, 2, 15000000, kings);
        playerRepository.save(aKempe);
        Player aAthanasiou = new Player("Andreas", "Athanasiou", 26, "Center", 3, 2, 15000000, kings);
        playerRepository.save(aAthanasiou);
        Player aIafallo = new Player("Alex", "Iafallo", 27, "Left Wing", 1, 3, 30000000, kings);
        playerRepository.save(aIafallo);
        Player tMoore = new Player("Trevor", "Moore", 26, "Left Wing", 2, 2, 15000000, kings);
        playerRepository.save(tMoore);
        Player aWagner = new Player("Austin", "Wagner", 24, "Left Wing", 3, 2, 15000000, kings);
        playerRepository.save(aWagner);
        Player dBrown = new Player("Dustin", "Brown", 36, "Right Wing", 1, 3, 30000000, kings);
        playerRepository.save(dBrown);
        Player gVilardi = new Player("Gabriel", "Vilardi", 21, "Right Wing", 2, 2, 15000000, kings);
        playerRepository.save(gVilardi);
        Player cGrundstrom = new Player("Carl", "Grundstrom", 23, "Right Wing", 3, 1, 5000000, kings);
        playerRepository.save(cGrundstrom);
        Player dDoughty = new Player("Drew", "Doughty", 31, "Defence", 1, 3, 30000000, kings);
        playerRepository.save(dDoughty);
        Player sWalker = new Player("Sean", "Walker", 26, "Defence", 1, 2, 15000000, kings);
        playerRepository.save(sWalker);
        Player mAnderson = new Player("Mikey", "Anderson", 22, "Defence", 2, 2, 15000000, kings);
        playerRepository.save(mAnderson);
        Player mRoy = new Player("Matt", "Roy", 26, "Defence", 2, 2, 15000000, kings);
        playerRepository.save(mRoy);
        Player tBjornfot = new Player("Tobias", "Bjornfot", 20, "Defence", 3, 1, 5000000, kings);
        playerRepository.save(tBjornfot);
        Player oMaatta = new Player("Olli", "Maatta", 26, "Defence", 3, 1, 5000000, kings);
        playerRepository.save(oMaatta);
        Player cPetersen = new Player("Calvin", "Petersen", 26, "Goaltender", 1, 3, 30000000, kings);
        playerRepository.save(cPetersen);
        Player jQuick = new Player("Jonathan", "Quick", 35, "Goaltender", 2, 1, 5000000, kings);
        playerRepository.save(jQuick);
        Player tGrosenick = new Player("Troy", "Grosenick", 31, "Goaltender", 3, 1, 5000000, kings);
        playerRepository.save(tGrosenick);

//        MINNESOTA WILD

        Player jErikssonEk = new Player("Joel", "Eriksson Ek", 24, "Center", 1, 2, 15000000, wild);
        playerRepository.save(jErikssonEk);
        Player nBonino = new Player("Nick", "Bonino", 33, "Center", 2, 2, 15000000, wild);
        playerRepository.save(nBonino);
        Player vRask = new Player("Victor", "Rask", 28, "Center", 3, 2, 15000000, wild);
        playerRepository.save(vRask);
        Player kKaprizov = new Player("Kirill", "Kaprizov", 24, "Left Wing", 1, 3, 30000000, wild);
        playerRepository.save(kKaprizov);
        Player kFiala = new Player("Kevin", "Fiala", 24, "Left Wing", 2, 3, 30000000, wild);
        playerRepository.save(kFiala);
        Player jGreenway = new Player("Jordan", "Greenway", 24, "Left Wing", 3, 2, 15000000, wild);
        playerRepository.save(jGreenway);
        Player mZuccarello = new Player("Mats", "Zuccarella", 33, "Right Wing", 1, 3, 30000000, wild);
        playerRepository.save(mZuccarello);
        Player rHartman = new Player("Ryan", "Hartman", 26, "Right Wing", 2, 2, 15000000, wild);
        playerRepository.save(rHartman);
        Player nBjugstad = new Player("Nick", "Bjugstad", 28, "Right Wing", 3, 1, 5000000, wild);
        playerRepository.save(nBjugstad);
        Player jSpurgeon = new Player("Jared", "Spurgeon", 31, "Defence", 1, 3, 30000000, wild);
        playerRepository.save(jSpurgeon);
        Player jBrodin = new Player("Jonas", "Brodin", 27, "Defence", 1, 2, 15000000, wild);
        playerRepository.save(jBrodin);
        Player mDumba = new Player("Matt", "Dumba", 26, "Defence", 2, 2, 15000000, wild);
        playerRepository.save(mDumba);
        Player rSuter = new Player("Ryan", "Suter", 36, "Defence", 2, 2, 15000000, wild);
        playerRepository.save(rSuter);
        Player cSoucy = new Player("Carson", "Soucy", 26, "Defence", 3, 2, 15000000, wild);
        playerRepository.save(cSoucy);
        Player iCole = new Player("Ian", "Cole", 32, "Defence", 3, 2, 15000000, wild);
        playerRepository.save(iCole);
        Player cTalbot = new Player("Cam", "Talbot", 33, "Goaltender", 1, 3, 30000000, wild);
        playerRepository.save(cTalbot);
        Player jRoss = new Player("John", "Ross", 28, "Goaltender", 2, 3, 30000000, wild);
        playerRepository.save(jRoss);
        Player kKahkonan = new Player("Kaapo", "Khakonan", 24, "Goaltender", 3, 2, 15000000, wild);
        playerRepository.save(kKahkonan);

//        MONTREAL CANADIENS

        Player nSuzuki = new Player("Nick", "Suzuki", 21, "Center", 1, 3, 30000000, habs);
        playerRepository.save(nSuzuki);
        Player pDanault = new Player("Phillip", "Danault", 28, "Center", 2, 2, 15000000, habs);
        playerRepository.save(pDanault);
        Player jKotkaniemi = new Player("Jesperi", "Kotkaniemi", 20, "Center", 3, 1, 5000000, habs);
        playerRepository.save(jKotkaniemi);
        Player tTatar = new Player("Tomas", "Tatar", 30, "Left Wing", 1, 3, 30000000, habs);
        playerRepository.save(tTatar);
        Player jDrouin = new Player("Jonathan", "Drouin", 26, "Left Wing", 2, 2, 15000000, habs);
        playerRepository.save(jDrouin);
        Player pByron = new Player("Paul", "Byron", 32, "Left Wing", 3, 1, 5000000, habs);
        playerRepository.save(pByron);
        Player tToffoli = new Player("Tyler", "Toffoli", 29, "Right Wing", 1, 3, 30000000, habs);
        playerRepository.save(tToffoli);
        Player jAnderson = new Player("Josh", "Anderson", 27, "Right Wing", 2, 2, 15000000, habs);
        playerRepository.save(jAnderson);
        Player bGallagher = new Player("Brendan", "Gallagher", 29, "Right Wing", 3, 2, 15000000, habs);
        playerRepository.save(bGallagher);
        Player jPetry = new Player("Jeff", "Petry", 33, "Defence", 1, 3, 30000000, habs);
        playerRepository.save(jPetry);
        Player sWeber = new Player("Shea", "Weber", 35, "Defence", 1, 2, 15000000, habs);
        playerRepository.save(sWeber);
        Player jEdmundson = new Player("Joel", "Edmundson", 28, "Defence", 2, 2, 15000000, habs);
        playerRepository.save(jEdmundson);
        Player bKulak = new Player("Brett", "Kulak", 27, "Defence", 2, 2, 15000000, habs);
        playerRepository.save(bKulak);
        Player bChiarot = new Player("Ben", "Chiarot", 30, "Defence", 3, 1, 5000000, habs);
        playerRepository.save(bChiarot);
        Player aRomanov = new Player("Alexander", "Romanov", 21, "Defence", 3, 1, 5000000, habs);
        playerRepository.save(aRomanov);
        Player jAllen = new Player("Jake", "Allen", 30, "Goaltender", 1, 2, 15000000, habs);
        playerRepository.save(jAllen);
        Player cPrice = new Player("Carey", "Price", 33, "Goaltender", 2, 2, 15000000, habs);
        playerRepository.save(cPrice);
        Player cPrimeau = new Player("Cayden", "Primeau", 21, "Goaltender", 3, 1, 5000000, habs);
        playerRepository.save(cPrimeau);

//        NASHVILLE PREDATORS

        Player cJarnkrok = new Player("Calle", "Jarnkrok", 29, "Center", 1, 2, 15000000, preds);
        playerRepository.save(cJarnkrok);
        Player mGranlund = new Player("Mikael", "Granlund", 29, "Center", 2, 2, 15000000, preds);
        playerRepository.save(mGranlund);
        Player rJohansen = new Player("Ryan", "Johansen", 28, "Center", 3, 1, 5000000, preds);
        playerRepository.save(rJohansen);
        Player fForsberg = new Player("Filip", "Forsberg", 26, "Left Wing", 1, 3, 30000000, preds);
        playerRepository.save(fForsberg);
        Player eHuala = new Player("Erik", "Huala", 30, "Left Wing", 2, 2, 15000000, preds);
        playerRepository.save(eHuala);
        Player nCousins = new Player("Nick", "Cousins", 27, "Left Wing", 3, 2, 15000000, preds);
        playerRepository.save(nCousins);
        Player vArvidsson = new Player("Viktor", "Arvidsson", 28, "Right Wing", 1, 2, 15000000, preds);
        playerRepository.save(vArvidsson);
        Player eTolvanen = new Player("Eeli", "Tolvanen", 22, "Right Wing", 2, 2, 15000000, preds);
        playerRepository.save(eTolvanen);
        Player rGrimaldi = new Player("Rocco", "Grimaldi", 28, "Right Wing", 3, 1, 5000000, preds);
        playerRepository.save(rGrimaldi);
        Player rJosi = new Player("Roman", "Josi", 31, "Defence", 1, 3, 30000000, preds);
        playerRepository.save(rJosi);
        Player mEkholm = new Player("Mattias", "Ekholm", 31, "Defence", 1, 2, 15000000, preds);
        playerRepository.save(mEkholm);
        Player rEllis = new Player("Ryan", "Ellis", 30, "Defence", 2, 2, 15000000, preds);
        playerRepository.save(rEllis);
        Player dFabbro = new Player("Dante", "Fabbro", 23, "Defence", 2, 2, 15000000, preds);
        playerRepository.save(dFabbro);
        Player bHarpur = new Player("Ben", "Harpur", 26, "Defence", 3, 1, 5000000, preds);
        playerRepository.save(bHarpur);
        Player mBenning = new Player("Matt", "Benning", 27, "Defence", 3, 1, 5000000, preds);
        playerRepository.save(mBenning);
        Player jSaros = new Player("Juuse", "Saros", 26, "Goaltender", 1, 3, 30000000, preds);
        playerRepository.save(jSaros);
        Player pRinne = new Player("Pekka", "Rinne", 38, "Goaltender", 2, 2, 15000000, preds);
        playerRepository.save(pRinne);
        Player kKaskisuo = new Player("Kasimir", "Kaskisuo", 27, "Goaltender", 3, 1, 5000000, preds);
        playerRepository.save(kKaskisuo);

//        NEW YORK ISLANDERS

        Player mBarzal = new Player("Mathew", "Barzal", 24, "Center", 1, 3, 30000000, isles);
        playerRepository.save(mBarzal);
        Player bNelson = new Player("Brock", "Nelson", 29, "Center", 2, 2, 15000000, isles);
        playerRepository.save(bNelson);
        Player jPageau = new Player("Jean-Gabriel", "Pageau", 28, "Center", 3, 2, 15000000, isles);
        playerRepository.save(jPageau);
        Player aBeauvillier = new Player("Anthony", "Beauvillier", 24, "Left Wing", 1, 2, 15000000, isles);
        playerRepository.save(aBeauvillier);
        Player aLee = new Player("Anders", "Lee", 30, "Left Wing", 2, 2, 15000000, isles);
        playerRepository.save(aLee);
        Player mMartin = new Player("Matt", "Martin", 32, "Left Wing", 3, 1, 5000000, isles);
        playerRepository.save(mMartin);
        Player jBailey = new Player("Josh", "Bailey", 31, "Right Wing", 1, 3, 30000000, isles);
        playerRepository.save(jBailey);
        Player jEberle = new Player("Jordan", "Eberle", 31, "Right Wing", 2, 3, 30000000, isles);
        playerRepository.save(jEberle);
        Player oWahlstrom = new Player("Oliver", "Wahlstrom", 21, "Right Wing", 3, 2, 15000000, isles);
        playerRepository.save(oWahlstrom);
        Player nLeddy = new Player("Nick", "Leddy", 30, "Defence", 1, 3, 30000000, isles);
        playerRepository.save(nLeddy);
        Player rPulock = new Player("Ryan", "Pulock", 26, "Defence", 1, 2, 15000000, isles);
        playerRepository.save(rPulock);
        Player sMayfield = new Player("Scott", "Mayfield", 28, "Defence", 2, 2, 15000000, isles);
        playerRepository.save(sMayfield);
        Player aPelech = new Player("Adam", "Pelech", 26, "Defence", 2, 2, 15000000, isles);
        playerRepository.save(aPelech);
        Player nDobson = new Player("Noah", "Dobson", 21, "Defence", 3, 2, 15000000, isles);
        playerRepository.save(nDobson);
        Player aGreene = new Player("Andy", "Greene", 38, "Defence", 3, 1, 5000000, isles);
        playerRepository.save(aGreene);
        Player sVarlamov = new Player("Semyon", "Varlamov", 33, "Goaltender", 1, 3, 30000000, isles);
        playerRepository.save(sVarlamov);
        Player iSorokin = new Player("Ilya", "Sorokin", 25, "Goaltender", 2, 3, 30000000, isles);
        playerRepository.save(iSorokin);
        Player cFarquhar = new Player("Colin", "Farquhar", 43, "Goaltender", 3, 2, 15000000, isles);
        playerRepository.save(cFarquhar);

//        NEW YORK RANGERS

        Player mZibanejad = new Player("Mika", "Zibanejad", 28, "Center", 1, 3, 30000000, rangers);
        playerRepository.save(mZibanejad);
        Player rStrome = new Player("Ryan", "Strome", 27, "Center", 2, 3, 30000000, rangers);
        playerRepository.save(rStrome);
        Player cBlackwell = new Player("Colin", "Blackwell", 28, "Center", 3, 2, 15000000, rangers);
        playerRepository.save(cBlackwell);
        Player aPanarin = new Player("Artemi", "Panarin", 29, "Left Wing", 1, 3, 30000000, rangers);
        playerRepository.save(aPanarin);
        Player cKreider = new Player("Chris", "Kreider", 30, "Left Wing", 2, 2, 15000000, rangers);
        playerRepository.save(cKreider);
        Player aLafreniere = new Player("Alexis", "Lafreniere", 19, "Left Wing", 3, 1, 5000000, rangers);
        playerRepository.save(aLafreniere);
        Player pBuchnevich = new Player("Pavel", "Buchnevich", 26, "Right Wing", 1, 3, 30000000, rangers);
        playerRepository.save(pBuchnevich);
        Player kKakko = new Player("Kaapo", "Kakko", 20, "Right Wing", 2, 1, 5000000, rangers);
        playerRepository.save(kKakko);
        Player kRooney = new Player("Kevin", "Rooney", 28, "Right Wing", 3, 1, 5000000, rangers);
        playerRepository.save(kRooney);
        Player aFox = new Player("Adam", "Fox", 23, "Defence", 1, 3, 30000000, rangers);
        playerRepository.save(aFox);
        Player rLindgren = new Player("Ryan", "Lindgren", 23, "Defence", 1, 3, 30000000, rangers);
        playerRepository.save(rLindgren);
        Player kMiller = new Player("K'Andre", "Miller", 21, "Defence", 2, 2, 15000000, rangers);
        playerRepository.save(kMiller);
        Player jTrouba = new Player("Jacob", "Trouba", 27, "Defence", 2, 2, 15000000, rangers);
        playerRepository.save(jTrouba);
        Player bSmith = new Player("Brendan", "Smith", 32, "Defence", 3, 2, 15000000, rangers);
        playerRepository.save(bSmith);
        Player lHajek = new Player("Libor", "Hajek", 23, "Defence", 3, 1, 5000000, rangers);
        playerRepository.save(lHajek);
        Player iShesterkin = new Player("Igor", "Shesterkin", 25, "Goaltender", 1, 3, 30000000, rangers);
        playerRepository.save(iShesterkin);
        Player aGeorgiev = new Player("Alexander", "Georgiev", 25, "Goaltender", 2, 2, 15000000, rangers);
        playerRepository.save(aGeorgiev);
        Player kKinkaid = new Player("Keith", "Kinkaid", 31, "Goaltender", 3, 1, 5000000, rangers);
        playerRepository.save(kKinkaid);

//        PHILADELPHIA FLYERS

        Player cGiroux = new Player("Claude", "Giroux", 33, "Center", 1, 3, 30000000, flyers);
        playerRepository.save(cGiroux);
        Player sCouturier = new Player("Sean", "Couturier", 28, "Center", 2, 3, 30000000, flyers);
        playerRepository.save(sCouturier);
        Player kHayes = new Player("Kevin", "Hayes", 29, "Center", 3, 2, 15000000, flyers);
        playerRepository.save(kHayes);
        Player jVanRiemsdyk = new Player("James", "Van Riemsdyk", 32, "Left Wing", 1, 3, 30000000, flyers);
        playerRepository.save(jVanRiemsdyk);
        Player jFarabee = new Player("Joel", "Farabee", 21, "Left Wing", 2, 3, 30000000, flyers);
        playerRepository.save(jFarabee);
        Player oLindblom = new Player("Oskar", "Lindblom", 24, "Left Wing", 3, 1, 5000000, flyers);
        playerRepository.save(oLindblom);
        Player jVoracek = new Player("Jakub", "Voracek", 31, "Right Wing", 1, 3, 30000000, flyers);
        playerRepository.save(jVoracek);
        Player tKonecny = new Player("Travis", "Konecny", 24, "Right Wing", 2, 3, 30000000, flyers);
        playerRepository.save(tKonecny);
        Player nAubeKubel = new Player("Nicolas", "Aube-Kubel", 25, "Right Wing", 3, 1, 5000000, flyers);
        playerRepository.save(nAubeKubel);
        Player iProvorov = new Player("Ivan", "Provorov", 24, "Defence", 1, 3, 30000000, flyers);
        playerRepository.save(iProvorov);
        Player sGostisbehere = new Player("Shayne", "Gostisbehere", 28, "Defence", 1, 2, 15000000, flyers);
        playerRepository.save(sGostisbehere);
        Player tSanheim = new Player("Travis", "Sanheim", 25, "Defence", 2, 1, 5000000, flyers);
        playerRepository.save(tSanheim);
        Player pMyers = new Player("Philippe", "Myers", 24, "Defence", 2, 1, 5000000, flyers);
        playerRepository.save(pMyers);
        Player jBraun = new Player("Justin", "Braun", 34, "Defence", 3, 1, 5000000, flyers);
        playerRepository.save(jBraun);
        Player rHagg = new Player("Robert", "Hagg", 26, "Defence", 3, 1, 5000000, flyers);
        playerRepository.save(rHagg);
        Player bElliott = new Player("Brian", "Elliott", 36, "Goaltender", 1, 1, 5000000, flyers);
        playerRepository.save(bElliott);
        Player cHart = new Player("Carter", "Hart", 22, "Goaltender", 2, 1, 5000000, flyers);
        playerRepository.save(cHart);
        Player aLyon = new Player("Alex", "Lyon", 28, "Goaltender", 3, 1, 5000000, flyers);
        playerRepository.save(aLyon);

//        PITTSBURGH PENGUINS

        Player sCrosby = new Player("Sidney", "Crosby", 33, "Center", 1, 3, 30000000, pens);
        playerRepository.save(sCrosby);
        Player eMalkin = new Player("Evgeni", "Malkin", 34, "Center", 2, 2, 15000000, pens);
        playerRepository.save(eMalkin);
        Player tBlueger = new Player("Teddy", "Blueger", 26, "Center", 3, 1, 5000000, pens);
        playerRepository.save(tBlueger);
        Player jGuentzel = new Player("Jake", "Guentzel", 26, "Left Wing", 1, 3, 30000000, pens);
        playerRepository.save(jGuentzel);
        Player jMcCann = new Player("Jared", "McCann", 25, "Left Wing", 2, 2, 15000000, pens);
        playerRepository.save(jMcCann);
        Player jZucker = new Player("Jason", "Zucker", 29, "Left Wing", 3, 2, 15000000, pens);
        playerRepository.save(jZucker);
        Player bRust = new Player("Bryan", "Rust", 29, "Right Wing", 1, 3, 30000000, pens);
        playerRepository.save(bRust);
        Player kKapanen = new Player("Kasperi", "Kapanen", 24, "Right Wing", 2, 3, 30000000, pens);
        playerRepository.save(kKapanen);
        Player cSceviour = new Player("Colton", "Sceviour", 32, "Right Wing", 3, 1, 5000000, pens);
        playerRepository.save(cSceviour);
        Player kLetang = new Player("Kris", "Letang", 34, "Defence", 1, 3, 30000000, pens);
        playerRepository.save(kLetang);
        Player cCeci = new Player("Cody", "Ceci", 27, "Defence", 1, 2, 15000000, pens);
        playerRepository.save(cCeci);
        Player mMatheson = new Player("Mike", "Matheson", 27, "Defence", 2, 2, 15000000, pens);
        playerRepository.save(mMatheson);
        Player bDumoulin = new Player("Brian", "Dumoulin", 29, "Defence", 2, 2, 15000000, pens);
        playerRepository.save(bDumoulin);
        Player jMarino = new Player("John", "Marino", 24, "Defence", 3, 2, 15000000, pens);
        playerRepository.save(jMarino);
        Player mPettersson = new Player("Marcus", "Pettersson", 25, "Defence", 3, 1, 5000000, pens);
        playerRepository.save(mPettersson);
        Player tJarry = new Player("Tristan", "Jarry", 26, "Goaltender", 1, 2, 15000000, pens);
        playerRepository.save(tJarry);
        Player cDeSmith = new Player("Casey", "DeSmith", 29, "Goaltender", 2, 2, 15000000, pens);
        playerRepository.save(cDeSmith);
        Player mLagace = new Player("Maxime", "Lagace", 28, "Goaltender", 3, 1, 5000000, pens);
        playerRepository.save(mLagace);

//        ST. LOUIS BLUES

        Player rOReilly = new Player("Ryan", "O'Reilly", 30, "Center", 1, 3, 30000000, blues);
        playerRepository.save(rOReilly);
        Player mHoffman = new Player("Mike", "Hoffman", 31, "Center", 2, 3, 30000000, blues);
        playerRepository.save(mHoffman);
        Player bSchenn = new Player("Brayden", "Schenn", 29, "Center", 3, 3, 30000000, blues);
        playerRepository.save(bSchenn);
        Player dPerron = new Player("David", "Perron", 33, "Left Wing", 1, 3, 30000000, blues);
        playerRepository.save(dPerron);
        Player jSchwartz = new Player("Jaden", "Schwartz", 29, "Left Wing", 2, 2, 15000000, blues);
        playerRepository.save(jSchwartz);
        Player zSanford = new Player("Zach", "Sanford", 26, "Left Wing", 3, 1, 5000000, blues);
        playerRepository.save(zSanford);
        Player jKyrou = new Player("Jordan", "Kyrou", 23, "Right Wing", 1, 3, 30000000, blues);
        playerRepository.save(jKyrou);
        Player tBozak = new Player("Tyler", "Bozak", 35, "Right Wing", 2, 2, 15000000, blues);
        playerRepository.save(tBozak);
        Player vTarasenko = new Player("Vladimir", "Tarasenko", 29, "Right Wing", 3, 1, 5000000, blues);
        playerRepository.save(vTarasenko);
        Player tKrug = new Player("Torey", "Krug", 30, "Defence", 1, 3, 30000000, blues);
        playerRepository.save(tKrug);
        Player jFaulk = new Player("Justin", "Faulk", 29, "Defence", 1, 3, 30000000, blues);
        playerRepository.save(jFaulk);
        Player vDunn = new Player("Vince", "Dunn", 24, "Defence", 2, 2, 15000000, blues);
        playerRepository.save(vDunn);
        Player cParayko = new Player("Colton", "Parayko", 28, "Defence", 2, 2, 15000000, blues);
        playerRepository.save(cParayko);
        Player mScandella = new Player("Marco", "Scandella", 31, "Defence", 3, 1, 5000000, blues);
        playerRepository.save(mScandella);
        Player rBortuzzo = new Player("Robert", "Bortuzzo", 32, "Defence", 3, 1, 5000000, blues);
        playerRepository.save(rBortuzzo);
        Player jBinnington = new Player("Jordan", "Binnington", 27, "Goaltender", 1, 3, 30000000, blues);
        playerRepository.save(jBinnington);
        Player vHusso = new Player("Ville", "Husso", 26, "Goaltender", 2, 1, 5000000, blues);
        playerRepository.save(vHusso);
        Player hGreen = new Player("Hannah", "Green", 26, "Goaltender", 3, 1, 5000000, blues);
        playerRepository.save(hGreen);

//        TAMPA BAY LIGHTNING

        Player bPoint = new Player("Brayden", "Point", 25, "Center", 1, 3, 30000000, tampa);
        playerRepository.save(bPoint);
        Player yGourde = new Player("Yanni", "Gourde", 29, "Center", 2, 3, 30000000, tampa);
        playerRepository.save(yGourde);
        Player bColeman = new Player("Blake", "Coleman", 29, "Center", 3, 2, 15000000, tampa);
        playerRepository.save(bColeman);
        Player oPalat = new Player("Ondrej", "Palat", 30, "Left Wing", 1, 3, 30000000, tampa);
        playerRepository.save(oPalat);
        Player aKillorn = new Player("Alex", "Killorn", 31, "Left Wing", 2, 3, 30000000, tampa);
        playerRepository.save(aKillorn);
        Player pMaroon = new Player("Pat", "Maroon", 33, "Left Wing", 3, 1, 5000000, tampa);
        playerRepository.save(pMaroon);
        Player sStamkos = new Player("Steven", "Stamkos", 31, "Right Wing", 1, 2, 15000000, tampa);
        playerRepository.save(sStamkos);
        Player mJoseph = new Player("Mathieu", "Joseph", 24, "Right Wing", 2, 1, 5000000, tampa);
        playerRepository.save(mJoseph);
        Player tJohnson = new Player("Tyler", "Johnson", 30, "Right Wing", 3, 1, 5000000, tampa);
        playerRepository.save(tJohnson);
        Player vHedman = new Player("Victor", "Hedman", 30, "Defence", 1, 3, 30000000, tampa);
        playerRepository.save(vHedman);
        Player mSergachev = new Player("Mikhail", "Sergachev", 23, "Defence", 1, 3, 30000000, tampa);
        playerRepository.save(mSergachev);
        Player eCernak = new Player("Erik", "Cernak", 24, "Defence", 2, 2, 15000000, tampa);
        playerRepository.save(eCernak);
        Player rMcDonagh = new Player("Ryan", "McDonagh", 32, "Defence", 2, 2, 15000000, tampa);
        playerRepository.save(rMcDonagh);
        Player jRutta = new Player("Jan", "Rutta", 30, "Defence", 3, 1, 5000000, tampa);
        playerRepository.save(jRutta);
        Player lSchenn = new Player("Luke", "Schenn", 31, "Defence", 3, 1, 5000000, tampa);
        playerRepository.save(lSchenn);
        Player aVasilevskiy = new Player("Andrei", "Vasilevskiy", 26, "Goaltender", 1, 3, 30000000, tampa);
        playerRepository.save(aVasilevskiy);
        Player cMcElhinney = new Player("Curtis", "McElhinney", 38, "Goaltender", 2, 1, 5000000, tampa);
        playerRepository.save(cMcElhinney);
        Player cGibson = new Player("Christopher", "Gibson", 28, "Goaltender", 3, 1, 5000000, tampa);
        playerRepository.save(cGibson);

//        TORONTO MAPLE LEAFS

        Player aMatthews = new Player("Auston", "Matthews", 23, "Center", 1, 3, 30000000, leafs);
        playerRepository.save(aMatthews);
        Player jTavares = new Player("John", "Tavares", 30, "Center", 2, 3, 30000000, leafs);
        playerRepository.save(jTavares);
        Player jSpezza = new Player("Jason", "Spezza", 38, "Center", 3, 2, 15000000, leafs);
        playerRepository.save(jSpezza);
        Player zHyman = new Player("Zach", "Hyman", 29, "Left Wing", 1, 3, 30000000, leafs);
        playerRepository.save(zHyman);
        Player aKerfoot = new Player("Alexander", "Kerfoot", 26, "Left Wing", 2, 2, 15000000, leafs);
        playerRepository.save(aKerfoot);
        Player pEngvall = new Player("Pierre", "Engvall", 25, "Left Wing", 3, 1, 5000000, leafs);
        playerRepository.save(pEngvall);
        Player mMarner = new Player("Mitchell", "Marner", 24, "Right Wing", 1, 3, 30000000, leafs);
        playerRepository.save(mMarner);
        Player wNylander = new Player("William", "Nylander", 25, "Right Wing", 2, 3, 30000000, leafs);
        playerRepository.save(wNylander);
        Player iMikheyev = new Player("Ilya", "Mikheyev", 26, "Right Wing", 3, 1, 5000000, leafs);
        playerRepository.save(iMikheyev);
        Player mRielly = new Player("Morgan", "Rielly", 27, "Defence", 1, 3, 30000000, leafs);
        playerRepository.save(mRielly);
        Player jMuzzin = new Player("Jake", "Muzzin", 32, "Defence", 1, 3, 30000000, leafs);
        playerRepository.save(jMuzzin);
        Player jHoll = new Player("Justin", "Holl", 29, "Defence", 2, 2, 15000000, leafs);
        playerRepository.save(jHoll);
        Player tBrodie = new Player("TJ", "Brodie", 31, "Defence", 2, 2, 15000000, leafs);
        playerRepository.save(tBrodie);
        Player zBogosian = new Player("Zach", "Bogosian", 30, "Defence", 3, 2, 15000000, leafs);
        playerRepository.save(zBogosian);
        Player tDermott = new Player("Travis", "Dermott", 24, "Defence", 3, 1, 5000000, leafs);
        playerRepository.save(tDermott);
        Player jCampbell = new Player("Jack", "Campbell", 29, "Goaltender", 1, 2, 15000000, leafs);
        playerRepository.save(jCampbell);
        Player fAndersen = new Player("Frederik", "Andersen", 31, "Goaltender", 2, 2, 15000000, leafs);
        playerRepository.save(fAndersen);
        Player mHutchinson = new Player("Michael", "Hutchinson", 31, "Goaltender", 3, 1, 5000000, leafs);
        playerRepository.save(mHutchinson);

//        VEGAS GOLDEN KNIGHTS

        Player jMarchessault = new Player("Jonathan", "Marchessault", 30, "Center", 1, 3, 30000000, knights);
        playerRepository.save(jMarchessault);
        Player wKarlsson = new Player("William", "Karlsson", 28, "Center", 2, 3, 30000000, knights);
        playerRepository.save(wKarlsson);
        Player cStephenson = new Player("Chandler", "Stephenson", 27, "Center", 3, 2, 15000000, knights);
        playerRepository.save(cStephenson);
        Player mPacioretty = new Player("Max", "Paccioretty", 32, "Left Wing", 1, 3, 30000000, knights);
        playerRepository.save(mPacioretty);
        Player tNosek = new Player("Tomas", "Nosek", 28, "Left Wing", 2, 1, 5000000, knights);
        playerRepository.save(tNosek);
        Player wCarrier = new Player("William", "Carrier", 26, "Left Wing", 3, 1, 5000000, knights);
        playerRepository.save(wCarrier);
        Player mStone = new Player("Mark", "Stone", 29, "Right Wing", 1, 3, 30000000, knights);
        playerRepository.save(mStone);
        Player aTuch = new Player("Alex", "Tuch", 25, "Right Wing", 2, 3, 30000000, knights);
        playerRepository.save(aTuch);
        Player rSmith = new Player("Reilly", "Smith", 30, "Right Wing", 3, 1, 5000000, knights);
        playerRepository.save(rSmith);
        Player sTheodore = new Player("Shea", "Theodore", 25, "Defence", 1, 3, 30000000, knights);
        playerRepository.save(sTheodore);
        Player aMartinez = new Player("Alec", "Martinez", 33, "Defence", 1, 3, 30000000, knights);
        playerRepository.save(aMartinez);
        Player aPietrangelo = new Player("Alex", "Pietrangelo", 31, "Defence", 2, 3, 30000000, knights);
        playerRepository.save(aPietrangelo);
        Player nHague = new Player("Nicolas", "Hague", 22, "Defence", 2, 2, 15000000, knights);
        playerRepository.save(nHague);
        Player zWhitecloud = new Player("Zach", "Whitecloud", 24, "Defence", 3, 2, 15000000, knights);
        playerRepository.save(zWhitecloud);
        Player bMcNabb = new Player("Brayden", "McNabb", 30, "Defence", 3, 2, 15000000, knights);
        playerRepository.save(bMcNabb);
        Player mFleury = new Player("Marc-Andre", "Fleury", 36, "Goaltender", 1, 3, 30000000, knights);
        playerRepository.save(mFleury);
        Player rLehner = new Player("Robin", "Lehner", 29, "Goaltender", 2, 2, 15000000, knights);
        playerRepository.save(rLehner);
        Player oDansk = new Player("Oscar", "Dansk", 27, "Goaltender", 3, 1, 5000000, knights);
        playerRepository.save(oDansk);

//        WASHINGTON CAPITALS

        Player nBackstrom = new Player("Nicklas", "Backstrom", 33, "Center", 1, 3, 30000000, caps);
        playerRepository.save(nBackstrom);
        Player eKuznetsov = new Player("Evgeny", "Kuznetsov", 29, "Center", 2, 2, 15000000, caps);
        playerRepository.save(eKuznetsov);
        Player lEller = new Player("Lars", "Eller", 32, "Center", 3, 2, 15000000, caps);
        playerRepository.save(lEller);
        Player aOvechkin = new Player("Alex", "Ovechkin", 35, "Left Wing", 1, 3, 30000000, caps);
        playerRepository.save(aOvechkin);
        Player cSheary = new Player("Conor", "Sheary", 29, "Left Wing", 2, 2, 15000000, caps);
        playerRepository.save(cSheary);
        Player cHagelin = new Player("Carl", "Hagelin", 32, "Left Wing", 3, 1, 5000000, caps);
        playerRepository.save(cHagelin);
        Player tOshie = new Player("T.J.", "Oshie", 34, "Right Wing", 1, 3, 30000000, caps);
        playerRepository.save(tOshie);
        Player tWilson = new Player("Tom", "Wilson", 27, "Right Wing", 2, 3, 30000000, caps);
        playerRepository.save(tWilson);
        Player dSprong = new Player("Daniel", "Sprong", 24, "Right Wing", 3, 1, 5000000, caps);
        playerRepository.save(dSprong);
        Player jCarlson = new Player("John", "Carlson", 31, "Defence", 1, 3, 30000000, caps);
        playerRepository.save(jCarlson);
        Player jSchultz = new Player("Justin", "Schultz", 30, "Defence", 1, 3, 30000000, caps);
        playerRepository.save(jSchultz);
        Player dOrlov = new Player("Dmitry", "Orlov", 29, "Defence", 2, 3, 30000000, caps);
        playerRepository.save(dOrlov);
        Player bDillon = new Player("Brenden", "Dillon", 30, "Defence", 2, 2, 15000000, caps);
        playerRepository.save(bDillon);
        Player nJensen = new Player("Nick", "Jensen", 30, "Defence", 3, 2, 15000000, caps);
        playerRepository.save(nJensen);
        Player zChara = new Player("Zdeno", "Chara", 44, "Defence", 3, 1, 5000000, caps);
        playerRepository.save(zChara);
        Player vVanecek = new Player("Vitek", "Vanecek", 25, "Goaltender", 1, 2, 15000000, caps);
        playerRepository.save(vVanecek);
        Player iSamsonov = new Player("Ilya", "Samsonov", 24, "Goaltender", 2, 2, 15000000, caps);
        playerRepository.save(iSamsonov);
        Player cAnderson = new Player("Craig", "Anderson", 40, "Goaltender", 3, 1, 5000000, caps);
        playerRepository.save(cAnderson);

//        WINNIPEG JETS

        Player mScheifele = new Player("Mark", "Scheifele", 28, "Center", 1, 3, 30000000, jets);
        playerRepository.save(mScheifele);
        Player aCopp = new Player("Andrew", "Copp", 26, "Center", 2, 3, 30000000, jets);
        playerRepository.save(aCopp);
        Player aLowry = new Player("Adam", "Lowry", 28, "Center", 3, 2, 15000000, jets);
        playerRepository.save(aLowry);
        Player kConnor = new Player("Kyle", "Connor", 24, "Left Wing", 1, 3, 30000000, jets);
        playerRepository.save(kConnor);
        Player nEhlers = new Player("Nikolaj", "Ehlers", 25, "Left Wing", 2, 3, 30000000, jets);
        playerRepository.save(nEhlers);
        Player pDubois = new Player("Pierre-Luc", "Dubois", 23, "Left Wing", 3, 2, 15000000, jets);
        playerRepository.save(pDubois);
        Player bWheeler = new Player("Blake", "Wheeler", 34, "Right Wing", 1, 3, 30000000, jets);
        playerRepository.save(bWheeler);
        Player pStastny = new Player("Paul", "Stastny", 35, "Right Wing", 2, 2, 15000000, jets);
        playerRepository.save(pStastny);
        Player mAppleton = new Player("Mason", "Appleton", 25, "Right Wing", 3, 2, 15000000, jets);
        playerRepository.save(mAppleton);
        Player nPionk = new Player("Neal", "Pionk", 25, "Defence", 1, 3, 30000000, jets);
        playerRepository.save(nPionk);
        Player jMorrissey = new Player("Josh", "Morrissey", 26, "Defence", 1, 2, 15000000, jets);
        playerRepository.save(jMorrissey);
        Player dForbort = new Player("Derek", "Forbort", 29, "Defence", 2, 2, 15000000, jets);
        playerRepository.save(dForbort);
        Player dDeMelo = new Player("Dylan", "DeMelo", 28, "Defence", 2, 2, 15000000, jets);
        playerRepository.save(dDeMelo);
        Player lStanley = new Player("Logan", "Stanley", 23, "Defence", 3, 2, 15000000, jets);
        playerRepository.save(lStanley);
        Player joBenn = new Player("Jordie", "Benn", 33, "Defence", 3, 1, 5000000, jets);
        playerRepository.save(joBenn);
        Player cHellebuyck = new Player("Connor", "Hellebuyck", 28, "Goaltender", 1, 3, 30000000, jets);
        playerRepository.save(cHellebuyck);
        Player lBrossoit = new Player("Laurent", "Brossoit", 28, "Goaltender", 2, 2, 15000000, jets);
        playerRepository.save(lBrossoit);
        Player rPaivansalo = new Player("Roosa", "Paivansalo", 28, "Goaltender", 3, 1, 5000000, jets);
        playerRepository.save(rPaivansalo);

//        FREE AGENTS

        Player tHertl = new Player("Tomas", "Hertl", 27, "Center", 1, 3, 30000000, free);
        playerRepository.save(tHertl);
        Player jNorris = new Player("Josh", "Norris", 22, "Center", 1, 3, 30000000, free);
        playerRepository.save(jNorris);
        Player cWilson = new Player("Craig", "Wilson", 31, "Center", 1, 3, 30000000, free);
        playerRepository.save(cWilson);
        Player dCallus = new Player("Daniel", "Callus", 33, "Center", 1, 3, 30000000, free);
        playerRepository.save(dCallus);
        Player nJack = new Player("Niall", "Jack", 31, "Center", 1, 3, 30000000, free);
        playerRepository.save(nJack);
        Player aHenrique = new Player("Adam", "Henrique", 31, "Center", 2, 2, 15000000, free);
        playerRepository.save(aHenrique);
        Player dLarkin = new Player("Dylan", "Larkin", 24, "Center", 2, 2, 15000000, free);
        playerRepository.save(dLarkin);
        Player lCouture = new Player("Logan", "Couture", 32, "Center", 2, 2, 15000000, free);
        playerRepository.save(lCouture);
        Player eStaal = new Player("Eric", "Staal", 36, "Center", 3, 1, 5000000, free);
        playerRepository.save(eStaal);
        Player cTierney = new Player("Chris", "Tierney", 26, "Center", 3, 1, 5000000, free);
        playerRepository.save(cTierney);
        Player bSutter = new Player("Brandon", "Sutter", 32, "Center", 3, 1, 5000000, free);
        playerRepository.save(bSutter);

        Player eKane = new Player("Evander", "Kane", 29, "Left Wing", 1, 3, 30000000, free);
        playerRepository.save(eKane);
        Player mComtois = new Player("Max", "Comtois", 22, "Left Wing", 1, 3, 30000000, free);
        playerRepository.save(mComtois);
        Player jMiller = new Player("Joshua", "Miller", 28, "Left Wing", 1, 3, 30000000, free);
        playerRepository.save(jMiller);
        Player gDerosas = new Player("Giuliano", "Derosas", 31, "Left Wing", 1, 3, 30000000, free);
        playerRepository.save(gDerosas);
        Player aKelly = new Player("Allen", "Kelly", 35, "Left Wing", 1, 3, 30000000, free);
        playerRepository.save(aKelly);
        Player jKuokkanen = new Player("Janne", "Kuokkanen", 23, "Left Wing", 2, 2, 15000000, free);
        playerRepository.save(jKuokkanen);
        Player nHoglander = new Player("Nils", "Hoglander", 20, "Left Wing", 2, 2, 15000000, free);
        playerRepository.save(nHoglander);
        Player pLaine = new Player("Patrik", "Laine", 23, "Left Wing", 2, 2, 15000000, free);
        playerRepository.save(pLaine);
        Player jSkinner = new Player("Jeff", "Skinner", 29, "Left Wing", 3, 1, 5000000, free);
        playerRepository.save(jSkinner);
        Player jLeonard = new Player("Lohn", "Leonard", 22, "Left Wing", 3, 1, 5000000, free);
        playerRepository.save(jLeonard);
        Player dHelm = new Player("Darren", "Helm", 34, "Left Wing", 3, 1, 5000000, free);
        playerRepository.save(dHelm);

        Player sReinhart = new Player("Sam", "Reinhart", 25, "Right Wing", 1, 3, 30000000, free);
        playerRepository.save(sReinhart);
        Player oBjorkstrand = new Player("Oliver", "Bjorkstrand", 26, "Right Wing", 1, 3, 30000000, free);
        playerRepository.save(oBjorkstrand);
        Player lBiel = new Player("Lina", "Biel", 31, "Right Wing", 1, 3, 30000000, free);
        playerRepository.save(lBiel);
        Player sSu = new Player("Sky", "Su", 33, "Right Wing", 1, 3, 30000000, free);
        playerRepository.save(sSu);
        Player uAshraf = new Player("Umair", "Ashraf", 30, "Right Wing", 1, 3, 30000000, free);
        playerRepository.save(uAshraf);
        Player fZadina = new Player("Filip", "Zadina", 21, "Right Wing", 2, 2, 15000000, free);
        playerRepository.save(fZadina);
        Player kLabanc = new Player("Kevin", "Labanc", 25, "Right Wing", 2, 2, 15000000, free);
        playerRepository.save(kLabanc);
        Player tTerry = new Player("Troy", "Terry", 23, "Right Wing", 2, 2, 15000000, free);
        playerRepository.save(tTerry);
        Player aVolkov = new Player("Alexander", "Volkov", 23, "Right Wing", 3, 1, 5000000, free);
        playerRepository.save(aVolkov);
        Player nBastian = new Player("Nathan", "Bastian", 23, "Right Wing", 3, 1, 5000000, free);
        playerRepository.save(nBastian);
        Player jVirtanen = new Player("Jake", "Virtanen", 24, "Right Wing", 3, 1, 5000000, free);
        playerRepository.save(jVirtanen);

        Player qHughes = new Player("Quinn", "Hughes", 21, "Defence", 1, 3, 30000000, free);
        playerRepository.save(qHughes);
        Player tChabot = new Player("Thomas", "Chabot", 24, "Defence", 1, 3, 30000000, free);
        playerRepository.save(tChabot);
        Player bBurns = new Player("Brent", "Burns", 36, "Defence", 1, 3, 30000000, free);
        playerRepository.save(bBurns);
        Player sJones = new Player("Seth", "Jones", 26, "Defence", 1, 3, 30000000, free);
        playerRepository.save(sJones);
        Player gLilley = new Player("Gordon", "Lilley", 40, "Defence", 1, 3, 30000000, free);
        playerRepository.save(gLilley);
        Player sMcCoy = new Player("Sam", "McCoy", 28, "Defence", 1, 3, 30000000, free);
        playerRepository.save(sMcCoy);
        Player aMcKie = new Player("Aaron", "McKie", 32, "Defence", 1, 3, 30000000, free);
        playerRepository.save(aMcKie);
        Player kLamb = new Player("Kieran", "Lamb", 31, "Defence", 1, 3, 30000000, free);
        playerRepository.save(kLamb);
        Player cFowler = new Player("Cam", "Fowler", 29, "Defence", 2, 2, 15000000, free);
        playerRepository.save(cFowler);
        Player kShattenkirk = new Player("Kevin", "Shattenkirk", 32, "Defence", 2, 2, 15000000, free);
        playerRepository.save(kShattenkirk);
        Player rDahlin = new Player("Rasmus", "Dahlin", 21, "Defence", 2, 2, 15000000, free);
        playerRepository.save(rDahlin);
        Player eKarlsson = new Player("Erik", "Karlsson", 31, "Defence", 2, 2, 15000000, free);
        playerRepository.save(eKarlsson);
        Player tSmith = new Player("Ty", "Smith", 21, "Defence", 2, 2, 15000000, free);
        playerRepository.save(tSmith);
        Player fHronek = new Player("Filip", "Hronek", 23, "Defence", 2, 2, 15000000, free);
        playerRepository.save(fHronek);
        Player vGavrikov = new Player("Vladislav", "Gavrikov", 25, "Defence", 3, 1, 5000000, free);
        playerRepository.save(vGavrikov);
        Player cMiller = new Player("Colin", "Miller", 28, "Defence", 3, 1, 5000000, free);
        playerRepository.save(cMiller);
        Player jaLarsson = new Player("Jacob", "Larsson", 24, "Defence", 3, 1, 5000000, free);
        playerRepository.save(jaLarsson);
        Player nZaitsev = new Player("Nikita", "Zaitsev", 29, "Defence", 3, 1, 5000000, free);
        playerRepository.save(nZaitsev);
        Player cDjoos = new Player("Christian", "Djoos", 26, "Defence", 3, 1, 5000000, free);
        playerRepository.save(cDjoos);
        Player nKnyzhov = new Player("Nikolai", "Knyzhov", 23, "Defence", 3, 1, 5000000, free);
        playerRepository.save(nKnyzhov);

        Player jBernier = new Player("Jonathan", "Bernier", 32, "Goaltender", 1, 3, 30000000, free);
        playerRepository.save(jBernier);
        Player tDemko = new Player("Thatcher", "Demko", 25, "Goaltender", 1, 3, 30000000, free);
        playerRepository.save(tDemko);
        Player wBlack = new Player("Wellington", "Black", 32, "Goaltender", 1, 3, 30000000, free);
        playerRepository.save(wBlack);
        Player mRae = new Player("Mark", "Rae", 29, "Goaltender", 1, 3, 30000000, free);
        playerRepository.save(mRae);
        Player aHigh = new Player("Andrew", "High", 34, "Goaltender", 1, 3, 30000000, free);
        playerRepository.save(aHigh);
        Player jGibson = new Player("John", "Gibson", 27, "Goaltender", 2, 2, 15000000, free);
        playerRepository.save(jGibson);
        Player lUllmark = new Player("Linus", "Ullmark", 27, "Goaltender", 2, 2, 15000000, free);
        playerRepository.save(lUllmark);
        Player eMerzlikins = new Player("Elvis", "Merzlikins", 27, "Goaltender", 2, 2, 15000000, free);
        playerRepository.save(eMerzlikins);
        Player bHoltby = new Player("Braden", "Holtby", 31, "Goaltender", 3, 1, 5000000, free);
        playerRepository.save(bHoltby);
        Player mJones = new Player("Martin", "Jones", 31, "Goaltender", 3, 1, 5000000, free);
        playerRepository.save(mJones);
        Player cPickard = new Player("Calvin", "Pickard", 29, "Goaltender", 3, 1, 5000000, free);
        playerRepository.save(cPickard);

    }
}
